## Runs configured build scripts and converts their directives into build options.

import std/[algorithm, json, os, options, strutils, tables]
import bau/[argv, config, features, util]

type
  BuildScriptResult* = object ## Directives emitted by configured build scripts.
    flags*: seq[string] ## Compiler flags emitted by scripts.
    generatedFiles*: seq[string] ## Files generated by scripts and tracked by builds.
    rerunFiles*: seq[string] ## Files that should invalidate the script cache.
    rerunEnv*: seq[string] ## Environment variables that invalidate the script cache.

  GeneratedFileRecord = object
    path: string
    hash: string
    exists: bool

  BuildScriptCacheRecord = object
    key: string
    result: BuildScriptResult
    generated: seq[GeneratedFileRecord]

proc withTemporaryEnv(env: Table[string, string]; body: proc()) =
  var oldValues = initTable[string, Option[string]]()
  for key, val in env.pairs:
    if existsEnv(key):
      oldValues[key] = some(getEnv(key))
    else:
      oldValues[key] = none(string)
    putEnv(key, val)
  try:
    body()
  finally:
    for key, old in oldValues.pairs:
      if old.isSome:
        putEnv(key, old.get())
      else:
        delEnv(key)

proc runScriptCommand(script: TaskInfo; projectDir: string;
    env: Table[string, string]): string =
  let cwd = script.cwd.get(projectDir)
  var command: string
  var args: seq[string]
  if script.shell.len > 0:
    command = script.shell
    args = @["-c", script.cmd]
  else:
    let parts = parseCommandLine(script.cmd)
    if parts.len == 0:
      raise newException(ValueError, "build script has an empty command: " &
        script.name)
    command = parts[0]
    args = if parts.len > 1: parts[1..^1] else: @[]

  var output = ""
  proc invoke() =
    let res = runCmd(command, args, cwd)
    output = res.output
    if res.exitCode != 0:
      raise newException(IOError, "build script '" & script.name &
        "' failed with exit code " & $res.exitCode & ":\n" & res.output)
  withTemporaryEnv(env, invoke)
  result = output

proc applyDirective(result: var BuildScriptResult; line: string) =
  let trimmed = line.strip()
  if not trimmed.startsWith("bau::"):
    return
  let payload = trimmed["bau::".len..^1]
  let parts = payload.split("=", 1)
  let key = parts[0]
  let value = if parts.len > 1: parts[1] else: ""
  case key
  of "rerun-if-changed":
    if value.len > 0:
      result.rerunFiles.add(value)
  of "rerun-if-env-changed":
    if value.len > 0:
      result.rerunEnv.add(value)
  of "nim-flag":
    if value.len > 0:
      result.flags.add(value)
  of "define":
    if value.len > 0:
      result.flags.add("-d:" & value)
  of "link-lib":
    if value.len > 0:
      result.flags.add("--passL:-l" & value)
  of "generated-file":
    if value.len > 0:
      result.generatedFiles.add(value)
  of "warning":
    warn(value)
  of "error":
    raise newException(ValueError, value)
  else:
    warn("unknown build script directive: " & key)

proc buildScriptEnv(script: TaskInfo; projectDir, profile: string;
    selection: FeatureSelection): Table[string, string] =
  result = enabledFeatureEnv(selection)
  result["BAU_PROJECT_DIR"] = projectDir
  result["BAU_PROFILE"] = profile
  result["BAU_OUT_DIR"] = projectDir / BuildDirName / "generated" / script.name
  createDir(result["BAU_OUT_DIR"])
  for key, val in script.env.pairs:
    result[key] = val

proc scriptCachePath(projectDir, scriptName: string): string =
  projectDir / BuildDirName / ".bau" / "buildscripts" /
    (scriptName.replace("/", "_").replace("\\", "_") & ".json")

proc addPathHash(content: var string; projectDir, path: string) =
  let absPath = if path.isAbsolute: path else: projectDir / path
  if fileExists(absPath):
    content.add(path & ":" & hashFile(absPath) & "\n")
  elif dirExists(absPath):
    var files: seq[string]
    for file in walkDirRec(absPath, yieldFilter = {pcFile}):
      if fileExists(file):
        files.add(file)
    files.sort()
    for file in files:
      content.add(relativePath(file, projectDir).replace("\\", "/") & ":" &
        hashFile(file) & "\n")
  else:
    content.add(path & ":missing\n")

proc pathDigest(projectDir, path: string): tuple[exists: bool; hash: string] =
  let absPath = if path.isAbsolute: path else: projectDir / path
  if fileExists(absPath):
    return (true, hashFile(absPath))
  if dirExists(absPath):
    var content = ""
    addPathHash(content, projectDir, path)
    return (true, hashStr(content))
  result = (false, "")

proc sortedEnvKeys(env: Table[string, string]): seq[string] =
  for key in env.keys:
    result.add(key)
  result.sort()

proc buildScriptCacheKey(script: TaskInfo; projectDir, profile: string;
    selection: FeatureSelection; previous: BuildScriptResult): string =
  var content = "script:" & script.name & "\n"
  content.add("cmd:" & script.cmd & "\n")
  content.add("cwd:" & script.cwd.get(projectDir) & "\n")
  content.add("profile:" & profile & "\n")
  content.add("platform:" & platformTriple() & "\n")
  content.add("nim:" & nimVersion() & "\n")
  for feature in selection.enabled:
    content.add("feature:" & feature & "\n")
  for dep in selection.enabledDeps:
    content.add("feature-dep:" & dep & "\n")
  for key in sortedEnvKeys(script.env):
    content.add("env:" & key & "=" & script.env[key] & "\n")
  for path in script.inputs:
    addPathHash(content, projectDir, path)
  for path in previous.rerunFiles:
    addPathHash(content, projectDir, path)
  for key in previous.rerunEnv:
    content.add("rerun-env:" & key & "=" & getEnv(key, "") & "\n")
  result = hashStr(content)

proc resultToJson(scriptResult: BuildScriptResult): JsonNode =
  %*{
    "flags": scriptResult.flags,
    "generatedFiles": scriptResult.generatedFiles,
    "rerunFiles": scriptResult.rerunFiles,
    "rerunEnv": scriptResult.rerunEnv
  }

proc resultFromJson(node: JsonNode): BuildScriptResult =
  if node.hasKey("flags"):
    for item in node["flags"].getElems():
      result.flags.add(item.getStr())
  if node.hasKey("generatedFiles"):
    for item in node["generatedFiles"].getElems():
      result.generatedFiles.add(item.getStr())
  if node.hasKey("rerunFiles"):
    for item in node["rerunFiles"].getElems():
      result.rerunFiles.add(item.getStr())
  if node.hasKey("rerunEnv"):
    for item in node["rerunEnv"].getElems():
      result.rerunEnv.add(item.getStr())

proc generatedToJson(records: openArray[GeneratedFileRecord]): JsonNode =
  result = newJArray()
  for record in records:
    result.add(%*{
      "path": record.path,
      "hash": record.hash,
      "exists": record.exists
    })

proc generatedFromJson(node: JsonNode): seq[GeneratedFileRecord] =
  if node.kind == JArray:
    for item in node.getElems():
      result.add(GeneratedFileRecord(
        path: item{"path"}.getStr(""),
        hash: item{"hash"}.getStr(""),
        exists: item{"exists"}.getBool(false)))

proc collectGeneratedRecords(projectDir: string;
    generatedFiles: openArray[string]): seq[GeneratedFileRecord] =
  for path in generatedFiles:
    let digest = pathDigest(projectDir, path)
    result.add(GeneratedFileRecord(path: path, hash: digest.hash,
      exists: digest.exists))

proc generatedRecordsValid(projectDir: string;
    scriptResult: BuildScriptResult; records: openArray[
        GeneratedFileRecord]): bool =
  if scriptResult.generatedFiles.len > 0 and records.len == 0:
    return false
  for record in records:
    let digest = pathDigest(projectDir, record.path)
    if not digest.exists:
      return false
    if not record.exists or digest.hash != record.hash:
      return false
  result = true

proc loadCachedScriptResult(path: string;
    record: var BuildScriptCacheRecord): bool =
  if not fileExists(path):
    return false
  try:
    let node = parseJson(readFileChecked(path))
    if node.hasKey("result"):
      record.result = resultFromJson(node["result"])
    if node.hasKey("generated"):
      record.generated = generatedFromJson(node["generated"])
    record.key = node{"key"}.getStr("")
    result = true
  except CatchableError:
    result = false

proc saveCachedScriptResult(path, key, projectDir: string;
    result: BuildScriptResult) =
  saveFile(path, $(%*{
    "key": key,
    "result": resultToJson(result),
    "generated": generatedToJson(collectGeneratedRecords(projectDir,
      result.generatedFiles))
  }))

proc runBuildScripts*(cfg: BauConfig; projectDir, profile: string;
    selection: FeatureSelection; verbose = false): BuildScriptResult =
  ## Run configured build scripts and collect their Bau directives.
  ##
  ## Script output lines beginning with `bau::` are interpreted as directives.
  for script in cfg.buildScripts:
    for required in script.requiredFeatures:
      if required notin selection.enabled:
        raise newException(ValueError, "build script '" & script.name &
          "' requires feature '" & required & "'")
    if verbose:
      info("build script: " & script.name)
    let cachePath = scriptCachePath(projectDir, script.name)
    var cached = BuildScriptCacheRecord()
    let hasCached = loadCachedScriptResult(cachePath, cached)
    let key = buildScriptCacheKey(script, projectDir, profile, selection,
      cached.result)
    if hasCached and cached.key == key and
        generatedRecordsValid(projectDir, cached.result, cached.generated):
      result.flags.add(cached.result.flags)
      result.generatedFiles.add(cached.result.generatedFiles)
      result.rerunFiles.add(cached.result.rerunFiles)
      result.rerunEnv.add(cached.result.rerunEnv)
    else:
      var scriptResult = BuildScriptResult()
      let output = runScriptCommand(script, projectDir,
        buildScriptEnv(script, projectDir, profile, selection))
      for line in output.splitLines():
        scriptResult.applyDirective(line)
      let finalKey = buildScriptCacheKey(script, projectDir, profile,
        selection, scriptResult)
      saveCachedScriptResult(cachePath, finalKey, projectDir, scriptResult)
      result.flags.add(scriptResult.flags)
      result.generatedFiles.add(scriptResult.generatedFiles)
      result.rerunFiles.add(scriptResult.rerunFiles)
      result.rerunEnv.add(scriptResult.rerunEnv)
