## Validates package contents and generates Nimble compatibility metadata.

import std/[algorithm, options, os, sets, strutils, tables]
import bau/[config, util]

proc hasPatternChars(path: string): bool =
  path.contains("*") or path.contains("?") or path.contains("[")

proc addCandidate(files: var HashSet[string]; projectDir, path: string) =
  let absPath = if path.isAbsolute: path else: projectDir / path
  if hasPatternChars(path):
    for f in walkPattern(absPath):
      if fileExists(f):
        files.incl(normalizedPath(f))
      elif dirExists(f):
        for child in walkDirRec(f, yieldFilter = {pcFile}):
          files.incl(normalizedPath(child))
  elif fileExists(absPath):
    files.incl(normalizedPath(absPath))
  elif dirExists(absPath):
    for f in walkDirRec(absPath, yieldFilter = {pcFile}):
      files.incl(normalizedPath(f))

proc defaultSkip(rel: string): bool =
  let top = rel.split("/")[0]
  (top.startsWith(".") and top notin [".gitignore"]) or
    rel.endsWith(".out") or rel.endsWith(".exe") or
    rel == ".git" or rel.startsWith(".git/") or
    rel == ".bau" or rel.startsWith(".bau/") or
    rel == "bin" or rel.startsWith("bin/") or
    rel == BuildDirName or rel.startsWith(BuildDirName & "/") or
    rel == "nimcache" or rel.startsWith("nimcache/") or
    rel == "nimblecache" or rel.startsWith("nimblecache/") or
    rel == "htmldocs" or rel.startsWith("htmldocs/") or
    rel == "nimbledirty" or rel == "compile_commands.json" or
    rel == "deps" or rel.startsWith("deps/")

proc collectPackageFiles*(projectDir: string; cfg: BauConfig): seq[string] =
  ## Return package-relative files selected for publication.
  ##
  ## Explicit include and exclude patterns from `[package]` are honored; when no
  ## includes are configured, Bau walks the project and skips build artifacts.
  var included = initHashSet[string]()
  if cfg.package.includeFiles.len > 0:
    for path in cfg.package.includeFiles:
      included.addCandidate(projectDir, path)
  else:
    for f in walkDirRec(projectDir, yieldFilter = {pcFile}):
      let rel = relativePath(f, projectDir).replace("\\", "/")
      if not defaultSkip(rel):
        included.incl(normalizedPath(f))

  var excluded = initHashSet[string]()
  for path in cfg.package.excludeFiles:
    excluded.addCandidate(projectDir, path)

  for f in included:
    if not excluded.contains(f):
      let rel = relativePath(f, projectDir).replace("\\", "/")
      if rel.len > 0 and not rel.startsWith(".."):
        result.add(rel)
  result.sort()

proc packageManifest*(projectDir: string; cfg: BauConfig): string =
  ## Build a textual package manifest for the selected package files.
  let files = collectPackageFiles(projectDir, cfg)
  if files.len == 0:
    raise newException(IOError, "package would be empty")
  result = "# package " & cfg.package.name & " " & cfg.package.version & "\n"
  for f in files:
    result.add(f & "\n")

proc verifyPackage*(projectDir: string; cfg: BauConfig) =
  ## Validate that a package has required metadata and non-empty contents.
  let files = collectPackageFiles(projectDir, cfg)
  if files.len == 0:
    raise newException(IOError, "package would be empty")
  if cfg.package.name.len == 0:
    raise newException(ValueError, "package.name is required")
  if cfg.package.version.len == 0:
    raise newException(ValueError, "package.version is required")

proc nimbleContent*(cfg: BauConfig): string =
  ## Generate Nimble compatibility metadata from Bau configuration.
  result = "# Generated by bau from bau.toml\n"
  result.add("version       = " & toTomlString(cfg.package.version) & "\n")
  result.add("author        = " & toTomlString(cfg.package.authors.join(", ")) & "\n")
  result.add("description   = " & toTomlString(cfg.package.description) & "\n")
  result.add("license       = " & toTomlString(cfg.package.license) & "\n")
  if cfg.build.source.len > 0:
    result.add("srcDir        = " & toTomlString(cfg.build.source) & "\n")
  if cfg.build.kind == bkBin:
    let outName = if cfg.build.output.len > 0: cfg.build.output else:
                    cfg.package.name
    result.add("bin           = @[" & toTomlString(outName) & "]\n")
  if cfg.toolchain.nim.len > 0:
    result.add("requires " & toTomlString("nim " & cfg.toolchain.nim) & "\n")
  var depNames: seq[string]
  for name in cfg.deps.keys:
    depNames.add(name)
  depNames.sort()
  for name in depNames:
    let dep = cfg.deps[name]
    if not dep.optional:
      if dep.version.isSome:
        result.add("requires " & toTomlString(name & " " &
          dep.version.get()) & "\n")
      elif dep.url.isNone and dep.path.isNone:
        result.add("requires " & toTomlString(name) & "\n")

proc hasLocalPublishOverrides*(cfg: BauConfig): bool =
  ## Return true when local patches or path dependencies block publishing.
  if cfg.patches.len > 0:
    return true
  for dep in cfg.deps.values:
    if dep.path.isSome:
      return true
