# Generated by bau from bau.toml
version       = "0.5.1"
author        = "bitstorm <bitstorm@tutanota.com>"
description   = "A modern build tool for Nim"
license       = "MIT"
srcDir        = "src"
bin           = @["bau"]
requires "nim >=2.2"
requires "parsetoml >=0.6.0"
