import std/[options, os, strutils, tables]
import bau/[lock, config]

proc findPackage(lockFile: LockFile; name: string): Option[ResolvedPackage] =
  for pkg in lockFile.packages.values:
    if pkg.id.name == name:
      return some(pkg)
  none(ResolvedPackage)

proc write(path, content: string) =
  createDir(parentDir(path))
  writeFile(path, content)

block lock_parse_v2_basic:
  let lockContent = """# bau.lock - @generated by bau, do not edit
version = 2
resolver = "atlas-bridge"
requirementsHash = "sha256:abc"
workspaceMembers = ["."]

[[rootDependency]]
name = "mylib"
requirement = ">=1.0"
source = "git+https://github.com/user/mylib.git#abc123"
url = "https://github.com/user/mylib.git"
workspaceMember = "."
enabledBy = []

[[package]]
name = "mylib"
version = "1.0.0"
source = "git+https://github.com/user/mylib.git#abc123"
revision = "abc123"
checksum = "sha256:deadbeef"
path = "deps/mylib"
direct = true
materialized = true
lockedAt = 1
enabledBy = []
dependencies = ["other|>=0.1|other 0.1.0 (registry+nimble://default)|false"]

[[package]]
name = "other"
version = "0.1.0"
source = "registry+nimble://default"
checksum = "sha256:cafebabe"
path = "deps/other"
materialized = true
lockedAt = 1
enabledBy = []
dependencies = []
"""

  let tmpFile = getTempDir() / "bau-test-bau-v2.lock"
  defer: removeFile(tmpFile)
  writeFile(tmpFile, lockContent)

  let parsed = parseLockFile(tmpFile)
  doAssert parsed.version == 2
  doAssert parsed.resolver == "atlas-bridge"
  doAssert parsed.rootDependencies.len == 1
  doAssert parsed.rootDependencies[0].name == "mylib"
  doAssert parsed.packages.len == 2
  let mylib = parsed.findPackage("mylib").get()
  doAssert mylib.id.version == "1.0.0"
  doAssert mylib.revision == "abc123"
  doAssert mylib.dependencies.len == 1
  doAssert mylib.dependencies[0].name == "other"

block lock_parse_empty:
  let parsed = parseLockFile("/nonexistent/bau.lock")
  doAssert parsed.version == 2
  doAssert parsed.packages.len == 0

block lock_rejects_v1:
  let tmpFile = getTempDir() / "bau-test-v1.lock"
  defer: removeFile(tmpFile)
  writeFile(tmpFile, "version = 1\n")
  var raised = false
  try:
    discard parseLockFile(tmpFile)
  except ValueError as e:
    raised = true
    doAssert "run bau deps lock" in e.msg
  doAssert raised

block lock_write_and_roundtrip:
  let tmpFile = getTempDir() / "bau-test-lock-v2-roundtrip.lock"
  defer: removeFile(tmpFile)

  var lockFile = initLockFile()
  lockFile.requirementsHash = "sha256:demo"
  lockFile.workspaceMembers = @["."]
  lockFile.rootDependencies.add(DependencyReq(
    name: "testpkg",
    requirement: ">=0.5",
    source: "registry+nimble://default",
    workspaceMember: "."))
  let dep = DependencyEdge(name: "other", requirement: ">=1.0",
    package: "other 1.0.0 (registry+nimble://default)")
  let pkg = ResolvedPackage(
    id: PackageId(name: "testpkg", version: "0.5.0",
      source: "registry+nimble://default"),
    dependencies: @[dep],
    checksum: "sha256:abc",
    path: "deps/testpkg",
    direct: true,
    materialized: true,
    lockedAt: 10)
  lockFile.packages[pkg.toString()] = pkg

  writeLockFile(lockFile, tmpFile)
  doAssert fileExists(tmpFile)

  let reRead = parseLockFile(tmpFile)
  doAssert reRead.version == 2
  doAssert reRead.rootDependencies.len == 1
  let testpkg = reRead.findPackage("testpkg").get()
  doAssert testpkg.id.version == "0.5.0"
  doAssert testpkg.dependencies.len == 1
  doAssert testpkg.dependencies[0].package ==
    "other 1.0.0 (registry+nimble://default)"

block lock_valid_check_and_tamper_detection:
  let tmp = getTempDir() / "bau-test-valid-v2"
  if dirExists(tmp):
    removeDir(tmp)
  defer:
    if dirExists(tmp):
      removeDir(tmp)

  write(tmp / "deps" / "pkg1" / "pkg1.nimble", "version = \"1.0.0\"\n")
  write(tmp / "deps" / "pkg1" / "src" / "pkg1.nim", "const pkg1* = 1\n")

  var cfg = initBauConfig()
  cfg.deps["pkg1"] = DepInfo(version: some(">=1.0"))

  let lockPath = tmp / LockFileName
  let lockFile = generateLockFile(cfg, tmp)
  writeLockFile(lockFile, lockPath)
  doAssert lockIsValid(cfg, lockPath, tmp)

  write(tmp / "deps" / "pkg1" / "src" / "pkg1.nim", "const pkg1* = 2\n")
  doAssert not lockIsValid(cfg, lockPath, tmp)

block lock_valid_missing_file:
  var cfg = initBauConfig()
  cfg.deps["pkg1"] = DepInfo(version: some(">=1.0"))
  doAssert not lockIsValid(cfg, "/nonexistent/file.lock")

block lock_uses_replaced_vendor_source_material:
  let tmp = getTempDir() / "bau-test-lock-source-replace"
  if dirExists(tmp):
    removeDir(tmp)
  defer:
    if dirExists(tmp):
      removeDir(tmp)

  write(tmp / "vendor" / "regpkg" / "regpkg.nimble", """
version = "2.0.0"
""")
  write(tmp / "vendor" / "regpkg" / "src" / "regpkg.nim",
    "const regpkg* = 2\n")

  var cfg = initBauConfig()
  cfg.deps["regpkg"] = DepInfo(version: some(">=1.0"),
    registry: some("mirror"))
  cfg.sources["mirror"] = SourceInfo(
    registry: "https://example.com/index",
    replaceWith: "vendor")
  cfg.sources["vendor"] = SourceInfo(directory: "vendor")

  let lockFile = generateLockFile(cfg, tmp)
  let pkg = lockFile.findPackage("regpkg").get()
  doAssert pkg.materialized
  doAssert pkg.id.version == "2.0.0"
  doAssert pkg.id.source == "vendor+vendor"
  doAssert pkg.path == "vendor/regpkg"
  doAssert unresolvedLockEntries(cfg, lockFile, tmp).len == 0

  let req = lockFile.rootDependencies[0]
  doAssert req.source == "vendor+vendor"

  let lockPath = tmp / LockFileName
  writeLockFile(lockFile, lockPath)
  doAssert lockIsValid(cfg, lockPath, tmp)
