import std/[os, strutils]
import bau/[config, configedit]

proc write(path, content: string) =
  createDir(parentDir(path))
  writeFile(path, content)

block semver_component_bumps:
  doAssert parseVersionBumpKind("--major") == vbMajor
  doAssert parseVersionBumpKind("minor") == vbMinor
  doAssert parseVersionBumpKind("PATCH") == vbPatch
  doAssert bumpedSemVer("1.2.3", vbPatch) == "1.2.4"
  doAssert bumpedSemVer("1.2.3", vbMinor) == "1.3.0"
  doAssert bumpedSemVer("1.2.3", vbMajor) == "2.0.0"
  doAssert bumpedSemVer("1.2.3-alpha+build.1", vbPatch) == "1.2.4"

block invalid_semver_is_rejected:
  var raised = false
  try:
    discard bumpedSemVer("1.2", vbPatch)
  except ValueError:
    raised = true
  doAssert raised

  raised = false
  try:
    discard bumpedSemVer("1.02.3", vbPatch)
  except ValueError:
    raised = true
  doAssert raised

block bump_package_version_updates_project_metadata:
  let tmp = getTempDir() / "bau-test-version-bump"
  if dirExists(tmp):
    removeDir(tmp)
  defer:
    if dirExists(tmp):
      removeDir(tmp)

  write(tmp / "bau.toml", """
[package]
name = "demo"
version = "1.2.3"

[dependencies]
other = { version = ">=1.0" }
""")
  write(tmp / "demo.nimble", """
# Generated by bau from bau.toml
version       = "1.2.3"
requires "other >=1.0"
""")

  let dryRun = bumpPackageVersion(tmp, vbMinor, dryRun = true)
  doAssert dryRun.oldVersion == "1.2.3"
  doAssert dryRun.newVersion == "1.3.0"
  doAssert parseBauConfigFile(tmp / "bau.toml").package.version == "1.2.3"
  doAssert readFile(tmp / "demo.nimble").contains("version       = \"1.2.3\"")

  let bumped = bumpPackageVersion(tmp, vbMinor)
  doAssert bumped.oldVersion == "1.2.3"
  doAssert bumped.newVersion == "1.3.0"
  doAssert bumped.nimbleChanged

  let configContent = readFile(tmp / "bau.toml")
  doAssert parseBauConfig(configContent).package.version == "1.3.0"
  doAssert configContent.contains("other = { version = \">=1.0\" }")
  doAssert readFile(tmp / "demo.nimble").contains("version       = \"1.3.0\"")
